//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erstick_Hangman.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Erstick_Hangman.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string aceptar {
            get {
                return ResourceManager.GetString("aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A D V E R S A R I O.
        /// </summary>
        public static string adversario {
            get {
                return ResourceManager.GetString("adversario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string apellidos {
            get {
                return ResourceManager.GetString("apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apodo.
        /// </summary>
        public static string apodo {
            get {
                return ResourceManager.GetString("apodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aqui se mostraran los errores de ambos.
        /// </summary>
        public static string aviso {
            get {
                return ResourceManager.GetString("aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe elegir una ficha.
        /// </summary>
        public static string avisoElegir {
            get {
                return ResourceManager.GetString("avisoElegir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ganador es:.
        /// </summary>
        public static string avisoGanador {
            get {
                return ResourceManager.GetString("avisoGanador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar partida.
        /// </summary>
        public static string buscarPartidas {
            get {
                return ResourceManager.GetString("buscarPartidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese la contraseña.
        /// </summary>
        public static string campoContraseniaVacio {
            get {
                return ResourceManager.GetString("campoContraseniaVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos son invalidos, ingrese datos permitidos.
        /// </summary>
        public static string camposInvalidos {
            get {
                return ResourceManager.GetString("camposInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos son obligatorios.
        /// </summary>
        public static string camposObligatorios {
            get {
                return ResourceManager.GetString("camposObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese un correo.
        /// </summary>
        public static string campoUserVacio {
            get {
                return ResourceManager.GetString("campoUserVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo invalido.
        /// </summary>
        public static string codigoInvalido {
            get {
                return ResourceManager.GetString("codigoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string confirmarContraseña {
            get {
                return ResourceManager.GetString("confirmarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar puntajes.
        /// </summary>
        public static string consultarPuntajes {
            get {
                return ResourceManager.GetString("consultarPuntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario y/o contraseña invalidas.
        /// </summary>
        public static string contraseñaInvalida {
            get {
                return ResourceManager.GetString("contraseñaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrasenia.
        /// </summary>
        public static string contrasenia {
            get {
                return ResourceManager.GetString("contrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string correo {
            get {
                return ResourceManager.GetString("correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se a enviado el correo de activacion a su correo.
        /// </summary>
        public static string correoEnviado {
            get {
                return ResourceManager.GetString("correoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo no cumple con el formato necesario.
        /// </summary>
        public static string correoInvalido {
            get {
                return ResourceManager.GetString("correoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo repetido.
        /// </summary>
        public static string correoRepetido {
            get {
                return ResourceManager.GetString("correoRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string crearPartida {
            get {
                return ResourceManager.GetString("crearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        public static string cuenta {
            get {
                return ResourceManager.GetString("cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta activada exitosamente.
        /// </summary>
        public static string cuentaActivada {
            get {
                return ResourceManager.GetString("cuentaActivada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificil.
        /// </summary>
        public static string dificil {
            get {
                return ResourceManager.GetString("dificil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificultad.
        /// </summary>
        public static string dificultad {
            get {
                return ResourceManager.GetString("dificultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elegir.
        /// </summary>
        public static string elegir {
            get {
                return ResourceManager.GetString("elegir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta eligiendo su ficha(personaje).
        /// </summary>
        public static string eligiendoFicha {
            get {
                return ResourceManager.GetString("eligiendoFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta realizando la seleccion de letra.
        /// </summary>
        public static string eligiendoPalabra {
            get {
                return ResourceManager.GetString("eligiendoPalabra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija su ficha:.
        /// </summary>
        public static string elijaFicha {
            get {
                return ResourceManager.GetString("elijaFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato de correo es invalido.
        /// </summary>
        public static string emailInvalido {
            get {
                return ResourceManager.GetString("emailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ha entrado a la sala.
        /// </summary>
        public static string entrarSala {
            get {
                return ResourceManager.GetString("entrarSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string enviar {
            get {
                return ResourceManager.GetString("enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar con la BD.
        /// </summary>
        public static string errorConexionBaseDatos {
            get {
                return ResourceManager.GetString("errorConexionBaseDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar con el servidor.
        /// </summary>
        public static string errorConexionServidor {
            get {
                return ResourceManager.GetString("errorConexionServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERRORES.
        /// </summary>
        public static string errores {
            get {
                return ResourceManager.GetString("errores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar el mensaje .
        /// </summary>
        public static string errorMandarCorreo {
            get {
                return ResourceManager.GetString("errorMandarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya se encuentra conectado.
        /// </summary>
        public static string errorUsuarioConectado {
            get {
                return ResourceManager.GetString("errorUsuarioConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error el usuario ya se encuentra desconectado.
        /// </summary>
        public static string errorUsuarioDesconectado {
            get {
                return ResourceManager.GetString("errorUsuarioDesconectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facil.
        /// </summary>
        public static string facil {
            get {
                return ResourceManager.GetString("facil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string fecha {
            get {
                return ResourceManager.GetString("fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string idiomaEncabezado {
            get {
                return ResourceManager.GetString("idiomaEncabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string idiomaEspañol {
            get {
                return ResourceManager.GetString("idiomaEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        public static string idiomaIngles {
            get {
                return ResourceManager.GetString("idiomaIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma palabra.
        /// </summary>
        public static string idiomaPalabra {
            get {
                return ResourceManager.GetString("idiomaPalabra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese el codigo recibido:.
        /// </summary>
        public static string ingresarCodigo {
            get {
                return ResourceManager.GetString("ingresarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de activación.
        /// </summary>
        public static string ingresarCodigoActivacion {
            get {
                return ResourceManager.GetString("ingresarCodigoActivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesion.
        /// </summary>
        public static string iniciarSesion {
            get {
                return ResourceManager.GetString("iniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores conectados de 2.
        /// </summary>
        public static string jugadoresConectados {
            get {
                return ResourceManager.GetString("jugadoresConectados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        public static string jugar {
            get {
                return ResourceManager.GetString("jugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejores puntajes.
        /// </summary>
        public static string mejoresPuntajes {
            get {
                return ResourceManager.GetString("mejoresPuntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no coincide.
        /// </summary>
        public static string noCoincideContraseña {
            get {
                return ResourceManager.GetString("noCoincideContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string nombreSala {
            get {
                return ResourceManager.GetString("nombreSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tiene cuenta?.
        /// </summary>
        public static string noTieneCuenta {
            get {
                return ResourceManager.GetString("noTieneCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero Jugadores.
        /// </summary>
        public static string numeroJugadores {
            get {
                return ResourceManager.GetString("numeroJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personales.
        /// </summary>
        public static string personales {
            get {
                return ResourceManager.GetString("personales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis puntajes.
        /// </summary>
        public static string puntajesPropios {
            get {
                return ResourceManager.GetString("puntajesPropios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos.
        /// </summary>
        public static string puntos {
            get {
                return ResourceManager.GetString("puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Re-Enviar.
        /// </summary>
        public static string reenviarCorreo {
            get {
                return ResourceManager.GetString("reenviarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string registrar {
            get {
                return ResourceManager.GetString("registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reglas.
        /// </summary>
        public static string reglas {
            get {
                return ResourceManager.GetString("reglas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string regresar {
            get {
                return ResourceManager.GetString("regresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string salir {
            get {
                return ResourceManager.GetString("salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ha salido de la sala .
        /// </summary>
        public static string salirSala {
            get {
                return ResourceManager.GetString("salirSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexion.
        /// </summary>
        public static string tituloErrorConexion {
            get {
                return ResourceManager.GetString("tituloErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turnos.
        /// </summary>
        public static string turnos {
            get {
                return ResourceManager.GetString("turnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a Partida.
        /// </summary>
        public static string unirsePartida {
            get {
                return ResourceManager.GetString("unirsePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Resources/Reglas/Reglas_Español.jpg.
        /// </summary>
        public static string uriReglas {
            get {
                return ResourceManager.GetString("uriReglas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a U S T E D.
        /// </summary>
        public static string usted {
            get {
                return ResourceManager.GetString("usted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario repetido.
        /// </summary>
        public static string usuarioRepetido {
            get {
                return ResourceManager.GetString("usuarioRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validacion de cuenta.
        /// </summary>
        public static string validarCuenta {
            get {
                return ResourceManager.GetString("validarCuenta", resourceCulture);
            }
        }
    }
}
