//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erstick_Hangman.ServicioErstick2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://schemas.datacontract.org/2004/07/MessageServiceE")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidadaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Validada {
            get {
                return this.ValidadaField;
            }
            set {
                if ((this.ValidadaField.Equals(value) != true)) {
                    this.ValidadaField = value;
                    this.RaisePropertyChanged("Validada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/MessageServiceE")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apodo {
            get {
                return this.ApodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoField, value) != true)) {
                    this.ApodoField = value;
                    this.RaisePropertyChanged("Apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilaTablaPuntajes", Namespace="http://schemas.datacontract.org/2004/07/MessageServiceE")]
    [System.SerializableAttribute()]
    public partial class FilaTablaPuntajes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apodo {
            get {
                return this.ApodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoField, value) != true)) {
                    this.ApodoField = value;
                    this.RaisePropertyChanged("Apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntos {
            get {
                return this.PuntosField;
            }
            set {
                if ((this.PuntosField.Equals(value) != true)) {
                    this.PuntosField = value;
                    this.RaisePropertyChanged("Puntos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Turnos {
            get {
                return this.TurnosField;
            }
            set {
                if ((this.TurnosField.Equals(value) != true)) {
                    this.TurnosField = value;
                    this.RaisePropertyChanged("Turnos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sala", Namespace="http://schemas.datacontract.org/2004/07/MessageServiceE")]
    [System.SerializableAttribute()]
    public partial class Sala : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<object, Erstick_Hangman.ServicioErstick2.Jugador> DiccionarioJugadoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<object, Erstick_Hangman.ServicioErstick2.Jugador> DiccionarioJugadoresLobbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Erstick_Hangman.ServicioErstick2.Ficha[] FichasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdiomaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JugadorEnTurnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] JugadoresJugandoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool JugandoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumJugadoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PalabraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<object, Erstick_Hangman.ServicioErstick2.Jugador> DiccionarioJugadores {
            get {
                return this.DiccionarioJugadoresField;
            }
            set {
                if ((object.ReferenceEquals(this.DiccionarioJugadoresField, value) != true)) {
                    this.DiccionarioJugadoresField = value;
                    this.RaisePropertyChanged("DiccionarioJugadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<object, Erstick_Hangman.ServicioErstick2.Jugador> DiccionarioJugadoresLobby {
            get {
                return this.DiccionarioJugadoresLobbyField;
            }
            set {
                if ((object.ReferenceEquals(this.DiccionarioJugadoresLobbyField, value) != true)) {
                    this.DiccionarioJugadoresLobbyField = value;
                    this.RaisePropertyChanged("DiccionarioJugadoresLobby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Erstick_Hangman.ServicioErstick2.Ficha[] Fichas {
            get {
                return this.FichasField;
            }
            set {
                if ((object.ReferenceEquals(this.FichasField, value) != true)) {
                    this.FichasField = value;
                    this.RaisePropertyChanged("Fichas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSala {
            get {
                return this.IdSalaField;
            }
            set {
                if ((this.IdSalaField.Equals(value) != true)) {
                    this.IdSalaField = value;
                    this.RaisePropertyChanged("IdSala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idioma {
            get {
                return this.IdiomaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdiomaField, value) != true)) {
                    this.IdiomaField = value;
                    this.RaisePropertyChanged("Idioma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JugadorEnTurno {
            get {
                return this.JugadorEnTurnoField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorEnTurnoField, value) != true)) {
                    this.JugadorEnTurnoField = value;
                    this.RaisePropertyChanged("JugadorEnTurno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] JugadoresJugando {
            get {
                return this.JugadoresJugandoField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadoresJugandoField, value) != true)) {
                    this.JugadoresJugandoField = value;
                    this.RaisePropertyChanged("JugadoresJugando");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Jugando {
            get {
                return this.JugandoField;
            }
            set {
                if ((this.JugandoField.Equals(value) != true)) {
                    this.JugandoField = value;
                    this.RaisePropertyChanged("Jugando");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumJugadores {
            get {
                return this.NumJugadoresField;
            }
            set {
                if ((this.NumJugadoresField.Equals(value) != true)) {
                    this.NumJugadoresField = value;
                    this.RaisePropertyChanged("NumJugadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Palabra {
            get {
                return this.PalabraField;
            }
            set {
                if ((object.ReferenceEquals(this.PalabraField, value) != true)) {
                    this.PalabraField = value;
                    this.RaisePropertyChanged("Palabra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ficha", Namespace="http://schemas.datacontract.org/2004/07/MessageServiceE")]
    [System.SerializableAttribute()]
    public partial class Ficha : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErroresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GanadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LetraGuardadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MovimientosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreFichaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UriFichaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApodoJugador {
            get {
                return this.ApodoJugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoJugadorField, value) != true)) {
                    this.ApodoJugadorField = value;
                    this.RaisePropertyChanged("ApodoJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Errores {
            get {
                return this.ErroresField;
            }
            set {
                if ((this.ErroresField.Equals(value) != true)) {
                    this.ErroresField = value;
                    this.RaisePropertyChanged("Errores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ganador {
            get {
                return this.GanadorField;
            }
            set {
                if ((this.GanadorField.Equals(value) != true)) {
                    this.GanadorField = value;
                    this.RaisePropertyChanged("Ganador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LetraGuardada {
            get {
                return this.LetraGuardadaField;
            }
            set {
                if ((object.ReferenceEquals(this.LetraGuardadaField, value) != true)) {
                    this.LetraGuardadaField = value;
                    this.RaisePropertyChanged("LetraGuardada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Movimientos {
            get {
                return this.MovimientosField;
            }
            set {
                if ((this.MovimientosField.Equals(value) != true)) {
                    this.MovimientosField = value;
                    this.RaisePropertyChanged("Movimientos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreFicha {
            get {
                return this.NombreFichaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreFichaField, value) != true)) {
                    this.NombreFichaField = value;
                    this.RaisePropertyChanged("NombreFicha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UriFicha {
            get {
                return this.UriFichaField;
            }
            set {
                if ((object.ReferenceEquals(this.UriFichaField, value) != true)) {
                    this.UriFichaField = value;
                    this.RaisePropertyChanged("UriFicha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioErstick2.IControlCuenta")]
    public interface IControlCuenta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/IniciarSesion", ReplyAction="http://tempuri.org/IControlCuenta/IniciarSesionResponse")]
        Erstick_Hangman.ServicioErstick2.Jugador IniciarSesion(Erstick_Hangman.ServicioErstick2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/IniciarSesion", ReplyAction="http://tempuri.org/IControlCuenta/IniciarSesionResponse")]
        System.Threading.Tasks.Task<Erstick_Hangman.ServicioErstick2.Jugador> IniciarSesionAsync(Erstick_Hangman.ServicioErstick2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/CerrarSesion", ReplyAction="http://tempuri.org/IControlCuenta/CerrarSesionResponse")]
        Erstick_Hangman.ServicioErstick2.Jugador CerrarSesion(Erstick_Hangman.ServicioErstick2.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/CerrarSesion", ReplyAction="http://tempuri.org/IControlCuenta/CerrarSesionResponse")]
        System.Threading.Tasks.Task<Erstick_Hangman.ServicioErstick2.Jugador> CerrarSesionAsync(Erstick_Hangman.ServicioErstick2.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/RegistrarJugador", ReplyAction="http://tempuri.org/IControlCuenta/RegistrarJugadorResponse")]
        int RegistrarJugador(Erstick_Hangman.ServicioErstick2.Jugador jugador, Erstick_Hangman.ServicioErstick2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/RegistrarJugador", ReplyAction="http://tempuri.org/IControlCuenta/RegistrarJugadorResponse")]
        System.Threading.Tasks.Task<int> RegistrarJugadorAsync(Erstick_Hangman.ServicioErstick2.Jugador jugador, Erstick_Hangman.ServicioErstick2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/ActivarCuentaJugador", ReplyAction="http://tempuri.org/IControlCuenta/ActivarCuentaJugadorResponse")]
        int ActivarCuentaJugador(Erstick_Hangman.ServicioErstick2.Cuenta cuenta, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/ActivarCuentaJugador", ReplyAction="http://tempuri.org/IControlCuenta/ActivarCuentaJugadorResponse")]
        System.Threading.Tasks.Task<int> ActivarCuentaJugadorAsync(Erstick_Hangman.ServicioErstick2.Cuenta cuenta, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/VerificarCuenta", ReplyAction="http://tempuri.org/IControlCuenta/VerificarCuentaResponse")]
        Erstick_Hangman.ServicioErstick2.Cuenta VerificarCuenta(Erstick_Hangman.ServicioErstick2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/VerificarCuenta", ReplyAction="http://tempuri.org/IControlCuenta/VerificarCuentaResponse")]
        System.Threading.Tasks.Task<Erstick_Hangman.ServicioErstick2.Cuenta> VerificarCuentaAsync(Erstick_Hangman.ServicioErstick2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/EnviarCorreo", ReplyAction="http://tempuri.org/IControlCuenta/EnviarCorreoResponse")]
        int EnviarCorreo(Erstick_Hangman.ServicioErstick2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/EnviarCorreo", ReplyAction="http://tempuri.org/IControlCuenta/EnviarCorreoResponse")]
        System.Threading.Tasks.Task<int> EnviarCorreoAsync(Erstick_Hangman.ServicioErstick2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/ConsultarPuntajesPropios", ReplyAction="http://tempuri.org/IControlCuenta/ConsultarPuntajesPropiosResponse")]
        Erstick_Hangman.ServicioErstick2.FilaTablaPuntajes[] ConsultarPuntajesPropios(Erstick_Hangman.ServicioErstick2.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/ConsultarPuntajesPropios", ReplyAction="http://tempuri.org/IControlCuenta/ConsultarPuntajesPropiosResponse")]
        System.Threading.Tasks.Task<Erstick_Hangman.ServicioErstick2.FilaTablaPuntajes[]> ConsultarPuntajesPropiosAsync(Erstick_Hangman.ServicioErstick2.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/ConsultarMejoresPuntajes", ReplyAction="http://tempuri.org/IControlCuenta/ConsultarMejoresPuntajesResponse")]
        Erstick_Hangman.ServicioErstick2.FilaTablaPuntajes[] ConsultarMejoresPuntajes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCuenta/ConsultarMejoresPuntajes", ReplyAction="http://tempuri.org/IControlCuenta/ConsultarMejoresPuntajesResponse")]
        System.Threading.Tasks.Task<Erstick_Hangman.ServicioErstick2.FilaTablaPuntajes[]> ConsultarMejoresPuntajesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControlCuentaChannel : Erstick_Hangman.ServicioErstick2.IControlCuenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControlCuentaClient : System.ServiceModel.ClientBase<Erstick_Hangman.ServicioErstick2.IControlCuenta>, Erstick_Hangman.ServicioErstick2.IControlCuenta {
        
        public ControlCuentaClient() {
        }
        
        public ControlCuentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControlCuentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlCuentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlCuentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Erstick_Hangman.ServicioErstick2.Jugador IniciarSesion(Erstick_Hangman.ServicioErstick2.Cuenta cuenta) {
            return base.Channel.IniciarSesion(cuenta);
        }
        
        public System.Threading.Tasks.Task<Erstick_Hangman.ServicioErstick2.Jugador> IniciarSesionAsync(Erstick_Hangman.ServicioErstick2.Cuenta cuenta) {
            return base.Channel.IniciarSesionAsync(cuenta);
        }
        
        public Erstick_Hangman.ServicioErstick2.Jugador CerrarSesion(Erstick_Hangman.ServicioErstick2.Jugador jugador) {
            return base.Channel.CerrarSesion(jugador);
        }
        
        public System.Threading.Tasks.Task<Erstick_Hangman.ServicioErstick2.Jugador> CerrarSesionAsync(Erstick_Hangman.ServicioErstick2.Jugador jugador) {
            return base.Channel.CerrarSesionAsync(jugador);
        }
        
        public int RegistrarJugador(Erstick_Hangman.ServicioErstick2.Jugador jugador, Erstick_Hangman.ServicioErstick2.Cuenta cuenta) {
            return base.Channel.RegistrarJugador(jugador, cuenta);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarJugadorAsync(Erstick_Hangman.ServicioErstick2.Jugador jugador, Erstick_Hangman.ServicioErstick2.Cuenta cuenta) {
            return base.Channel.RegistrarJugadorAsync(jugador, cuenta);
        }
        
        public int ActivarCuentaJugador(Erstick_Hangman.ServicioErstick2.Cuenta cuenta, string codigo) {
            return base.Channel.ActivarCuentaJugador(cuenta, codigo);
        }
        
        public System.Threading.Tasks.Task<int> ActivarCuentaJugadorAsync(Erstick_Hangman.ServicioErstick2.Cuenta cuenta, string codigo) {
            return base.Channel.ActivarCuentaJugadorAsync(cuenta, codigo);
        }
        
        public Erstick_Hangman.ServicioErstick2.Cuenta VerificarCuenta(Erstick_Hangman.ServicioErstick2.Cuenta cuenta) {
            return base.Channel.VerificarCuenta(cuenta);
        }
        
        public System.Threading.Tasks.Task<Erstick_Hangman.ServicioErstick2.Cuenta> VerificarCuentaAsync(Erstick_Hangman.ServicioErstick2.Cuenta cuenta) {
            return base.Channel.VerificarCuentaAsync(cuenta);
        }
        
        public int EnviarCorreo(Erstick_Hangman.ServicioErstick2.Cuenta cuenta) {
            return base.Channel.EnviarCorreo(cuenta);
        }
        
        public System.Threading.Tasks.Task<int> EnviarCorreoAsync(Erstick_Hangman.ServicioErstick2.Cuenta cuenta) {
            return base.Channel.EnviarCorreoAsync(cuenta);
        }
        
        public Erstick_Hangman.ServicioErstick2.FilaTablaPuntajes[] ConsultarPuntajesPropios(Erstick_Hangman.ServicioErstick2.Jugador jugador) {
            return base.Channel.ConsultarPuntajesPropios(jugador);
        }
        
        public System.Threading.Tasks.Task<Erstick_Hangman.ServicioErstick2.FilaTablaPuntajes[]> ConsultarPuntajesPropiosAsync(Erstick_Hangman.ServicioErstick2.Jugador jugador) {
            return base.Channel.ConsultarPuntajesPropiosAsync(jugador);
        }
        
        public Erstick_Hangman.ServicioErstick2.FilaTablaPuntajes[] ConsultarMejoresPuntajes() {
            return base.Channel.ConsultarMejoresPuntajes();
        }
        
        public System.Threading.Tasks.Task<Erstick_Hangman.ServicioErstick2.FilaTablaPuntajes[]> ConsultarMejoresPuntajesAsync() {
            return base.Channel.ConsultarMejoresPuntajesAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioErstick2.IControlJuego", CallbackContract=typeof(Erstick_Hangman.ServicioErstick2.IControlJuegoCallback))]
    public interface IControlJuego {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlJuego/CrearSala", ReplyAction="http://tempuri.org/IControlJuego/CrearSalaResponse")]
        int CrearSala(Erstick_Hangman.ServicioErstick2.Sala sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlJuego/CrearSala", ReplyAction="http://tempuri.org/IControlJuego/CrearSalaResponse")]
        System.Threading.Tasks.Task<int> CrearSalaAsync(Erstick_Hangman.ServicioErstick2.Sala sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlJuego/ConsultarSalasDisponibles", ReplyAction="http://tempuri.org/IControlJuego/ConsultarSalasDisponiblesResponse")]
        Erstick_Hangman.ServicioErstick2.Sala[] ConsultarSalasDisponibles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlJuego/ConsultarSalasDisponibles", ReplyAction="http://tempuri.org/IControlJuego/ConsultarSalasDisponiblesResponse")]
        System.Threading.Tasks.Task<Erstick_Hangman.ServicioErstick2.Sala[]> ConsultarSalasDisponiblesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlJuego/ConsultarJugadoresSala", ReplyAction="http://tempuri.org/IControlJuego/ConsultarJugadoresSalaResponse")]
        string[] ConsultarJugadoresSala(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlJuego/ConsultarJugadoresSala", ReplyAction="http://tempuri.org/IControlJuego/ConsultarJugadoresSalaResponse")]
        System.Threading.Tasks.Task<string[]> ConsultarJugadoresSalaAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/UnirseSala")]
        void UnirseSala(int idSala, Erstick_Hangman.ServicioErstick2.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/UnirseSala")]
        System.Threading.Tasks.Task UnirseSalaAsync(int idSala, Erstick_Hangman.ServicioErstick2.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlJuego/ValidarSala", ReplyAction="http://tempuri.org/IControlJuego/ValidarSalaResponse")]
        bool ValidarSala(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlJuego/ValidarSala", ReplyAction="http://tempuri.org/IControlJuego/ValidarSalaResponse")]
        System.Threading.Tasks.Task<bool> ValidarSalaAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/EnviarMensaje")]
        void EnviarMensaje(int idSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/EnviarMensaje")]
        System.Threading.Tasks.Task EnviarMensajeAsync(int idSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/SalirChat")]
        void SalirChat(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/SalirChat")]
        System.Threading.Tasks.Task SalirChatAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/IniciarJuego")]
        void IniciarJuego(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/IniciarJuego")]
        System.Threading.Tasks.Task IniciarJuegoAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/UnirseJuego")]
        void UnirseJuego(int idSala, Erstick_Hangman.ServicioErstick2.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/UnirseJuego")]
        System.Threading.Tasks.Task UnirseJuegoAsync(int idSala, Erstick_Hangman.ServicioErstick2.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/EnviarMensajeJuego")]
        void EnviarMensajeJuego(int idSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/EnviarMensajeJuego")]
        System.Threading.Tasks.Task EnviarMensajeJuegoAsync(int idSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/SalirJuego")]
        void SalirJuego(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/SalirJuego")]
        System.Threading.Tasks.Task SalirJuegoAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/AsignarFicha")]
        void AsignarFicha(int idSala, Erstick_Hangman.ServicioErstick2.Ficha ficha);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/AsignarFicha")]
        System.Threading.Tasks.Task AsignarFichaAsync(int idSala, Erstick_Hangman.ServicioErstick2.Ficha ficha);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/RecibirTiro")]
        void RecibirTiro(int idSala, int errores, string letraPasada, Erstick_Hangman.ServicioErstick2.Ficha ficha);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/RecibirTiro")]
        System.Threading.Tasks.Task RecibirTiroAsync(int idSala, int errores, string letraPasada, Erstick_Hangman.ServicioErstick2.Ficha ficha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControlJuegoCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/RecibirMensajeLobby")]
        void RecibirMensajeLobby(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/RecibirMensajeMiembroLobby")]
        void RecibirMensajeMiembroLobby(bool entrada, string apodo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/EntrarJuego")]
        void EntrarJuego();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/RecibirMensaje")]
        void RecibirMensaje(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/RecibirMensajeMiembro")]
        void RecibirMensajeMiembro(bool entrada, string apodo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/ElegirFicha")]
        void ElegirFicha(string apodo, Erstick_Hangman.ServicioErstick2.Ficha[] fichasEscogidas);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/MostrarFichaElegida")]
        void MostrarFichaElegida(Erstick_Hangman.ServicioErstick2.Ficha ficha);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/Tirar")]
        void Tirar(string apodo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/MostrarTiro")]
        void MostrarTiro(Erstick_Hangman.ServicioErstick2.Ficha ficha);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/MostrarGanador")]
        void MostrarGanador(Erstick_Hangman.ServicioErstick2.Ficha ficha);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/MostrarFichaElegida2")]
        void MostrarFichaElegida2(Erstick_Hangman.ServicioErstick2.Ficha ficha);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IControlJuego/MostrarErrorPlayerAuxiliar")]
        void MostrarErrorPlayerAuxiliar(Erstick_Hangman.ServicioErstick2.Ficha ficha, Erstick_Hangman.ServicioErstick2.Ficha ficha2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlJuego/ActualizarErrores", ReplyAction="http://tempuri.org/IControlJuego/ActualizarErroresResponse")]
        int ActualizarErrores(Erstick_Hangman.ServicioErstick2.Ficha ficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlJuego/ActualizarGanador", ReplyAction="http://tempuri.org/IControlJuego/ActualizarGanadorResponse")]
        int ActualizarGanador(Erstick_Hangman.ServicioErstick2.Ficha ficha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControlJuegoChannel : Erstick_Hangman.ServicioErstick2.IControlJuego, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControlJuegoClient : System.ServiceModel.DuplexClientBase<Erstick_Hangman.ServicioErstick2.IControlJuego>, Erstick_Hangman.ServicioErstick2.IControlJuego {
        
        public ControlJuegoClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ControlJuegoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ControlJuegoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ControlJuegoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ControlJuegoClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int CrearSala(Erstick_Hangman.ServicioErstick2.Sala sala) {
            return base.Channel.CrearSala(sala);
        }
        
        public System.Threading.Tasks.Task<int> CrearSalaAsync(Erstick_Hangman.ServicioErstick2.Sala sala) {
            return base.Channel.CrearSalaAsync(sala);
        }
        
        public Erstick_Hangman.ServicioErstick2.Sala[] ConsultarSalasDisponibles() {
            return base.Channel.ConsultarSalasDisponibles();
        }
        
        public System.Threading.Tasks.Task<Erstick_Hangman.ServicioErstick2.Sala[]> ConsultarSalasDisponiblesAsync() {
            return base.Channel.ConsultarSalasDisponiblesAsync();
        }
        
        public string[] ConsultarJugadoresSala(int idSala) {
            return base.Channel.ConsultarJugadoresSala(idSala);
        }
        
        public System.Threading.Tasks.Task<string[]> ConsultarJugadoresSalaAsync(int idSala) {
            return base.Channel.ConsultarJugadoresSalaAsync(idSala);
        }
        
        public void UnirseSala(int idSala, Erstick_Hangman.ServicioErstick2.Jugador jugador) {
            base.Channel.UnirseSala(idSala, jugador);
        }
        
        public System.Threading.Tasks.Task UnirseSalaAsync(int idSala, Erstick_Hangman.ServicioErstick2.Jugador jugador) {
            return base.Channel.UnirseSalaAsync(idSala, jugador);
        }
        
        public bool ValidarSala(int idSala) {
            return base.Channel.ValidarSala(idSala);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarSalaAsync(int idSala) {
            return base.Channel.ValidarSalaAsync(idSala);
        }
        
        public void EnviarMensaje(int idSala, string mensaje) {
            base.Channel.EnviarMensaje(idSala, mensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeAsync(int idSala, string mensaje) {
            return base.Channel.EnviarMensajeAsync(idSala, mensaje);
        }
        
        public void SalirChat(int idSala) {
            base.Channel.SalirChat(idSala);
        }
        
        public System.Threading.Tasks.Task SalirChatAsync(int idSala) {
            return base.Channel.SalirChatAsync(idSala);
        }
        
        public void IniciarJuego(int idSala) {
            base.Channel.IniciarJuego(idSala);
        }
        
        public System.Threading.Tasks.Task IniciarJuegoAsync(int idSala) {
            return base.Channel.IniciarJuegoAsync(idSala);
        }
        
        public void UnirseJuego(int idSala, Erstick_Hangman.ServicioErstick2.Jugador jugador) {
            base.Channel.UnirseJuego(idSala, jugador);
        }
        
        public System.Threading.Tasks.Task UnirseJuegoAsync(int idSala, Erstick_Hangman.ServicioErstick2.Jugador jugador) {
            return base.Channel.UnirseJuegoAsync(idSala, jugador);
        }
        
        public void EnviarMensajeJuego(int idSala, string mensaje) {
            base.Channel.EnviarMensajeJuego(idSala, mensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeJuegoAsync(int idSala, string mensaje) {
            return base.Channel.EnviarMensajeJuegoAsync(idSala, mensaje);
        }
        
        public void SalirJuego(int idSala) {
            base.Channel.SalirJuego(idSala);
        }
        
        public System.Threading.Tasks.Task SalirJuegoAsync(int idSala) {
            return base.Channel.SalirJuegoAsync(idSala);
        }
        
        public void AsignarFicha(int idSala, Erstick_Hangman.ServicioErstick2.Ficha ficha) {
            base.Channel.AsignarFicha(idSala, ficha);
        }
        
        public System.Threading.Tasks.Task AsignarFichaAsync(int idSala, Erstick_Hangman.ServicioErstick2.Ficha ficha) {
            return base.Channel.AsignarFichaAsync(idSala, ficha);
        }
        
        public void RecibirTiro(int idSala, int errores, string letraPasada, Erstick_Hangman.ServicioErstick2.Ficha ficha) {
            base.Channel.RecibirTiro(idSala, errores, letraPasada, ficha);
        }
        
        public System.Threading.Tasks.Task RecibirTiroAsync(int idSala, int errores, string letraPasada, Erstick_Hangman.ServicioErstick2.Ficha ficha) {
            return base.Channel.RecibirTiroAsync(idSala, errores, letraPasada, ficha);
        }
    }
}
